- name: "prereqs"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    state: present

- name: "add Docker repository key"
  apt_key:
    id: 0EBFCD88
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: "add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: 'docker'
    state: present
  register: dockerrepo

- name: "update from new repo"
  when: dockerrepo.changed
  apt:
    update_cache: yes

- name: "install Docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python-docker
      - python3-docker
      - pass
    state: present

- name: "set Docker's MTU to match MTU of the machine (needed on OpenStack)"
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
       "mtu": {{ ansible_default_ipv4.mtu }}
      }
  register: mtu

- name: "restart Docker after changing MTU"
  when: mtu.changed
  service:
    name: docker
    state: restarted

# install Portainer web app for managing containers
- name: "create volume for portainer"
  docker_volume:
    name: portainer_data

- name: "create password file"
  copy:
    dest: "{{ perun_certs_dir }}/portainer_admin_password.txt"
    content: "{{ perun_portainer_admin_password }}"
    owner: root
    group: perun
    mode: '0640'

- name: "list normal portainer volumes"
  set_fact:
    portainer_mounts:
      - { type: bind, source: /var/run/docker.sock, target: /var/run/docker.sock }
      - { type: volume, source: portainer_data, target: /data }
      - { type: bind, source: "{{ perun_certs_dir }}", target: "{{ perun_certs_dir }}", read_only: yes }

- name: "add certbot dirs to portainer volumes"
  when: perun_use_certbot_certificates
  set_fact:
    portainer_mounts: "{{ portainer_mounts + perun_certbot_mounts }}"

- name: "install portainer container"
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    pull:  yes
    restart_policy: always
    command: "-H unix:///var/run/docker.sock --ssl --sslcert {{ perun_certificate_fullchain_file }} --sslkey {{ perun_certificate_key_file }} --admin-password-file {{ perun_certs_dir }}/portainer_admin_password.txt"
    ports:
      - 9000:9000
    mounts: "{{ portainer_mounts }}"
  register: portainer_container

- name: "login into gitlab docker registry"
  docker_login:
    registry_url: "registry.gitlab.ics.muni.cz:443"
# perun_docker only:
#    username: "gitlab-read-only-deploy-token-perun-docker"
#    password: "K3tG1Np-yLVWB51jj3bB"
# whole perun:
    username: "gitlab-read-only-deploy-token-perun-all"
    password: "BgdJHJ_gsmyqp3se5WRx"

- name: "create a local Docker network for Perun"
  docker_network:
    name: perun_net
    driver_options:
      com.docker.network.driver.mtu: 1442
    ipam_config:
      - subnet: 192.168.0.0/24
        gateway: 192.168.0.1
