- name: "set cn=config attribute olcAttributeOptions: x-ns-"
  ldap_attr:
    dn: cn=config
    name: olcAttributeOptions
    values: "x-ns-"
    state: present

- name: "create entry for schema perun"
  ldap_entry:
    dn: cn={4}perun,cn=schema,cn=config
    objectClass: olcSchemaConfig
  register: perun_schema_entry
- name: "download schema perun file"
  get_url:
    url: "https://raw.githubusercontent.com/CESNET/perun/{{ perun_ldap_schemas_perun_version }}/perun-utils/ldapc-scripts/schemas/perun-schema.ldif"
    dest: "/etc/ldap/perun-schema.ldif"
    force: yes
  register: perun_schema_file
- name: "set up schema perun"
  command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  /etc/ldap/perun-schema.ldif"
  when: perun_schema_entry.changed or perun_schema_file.changed

- name: "create entry for schema inetUser"
  ldap_entry:
    dn: cn={5}inetUser,cn=schema,cn=config
    objectClass: olcSchemaConfig
  register: inetUser_schema_entry
- name: "download schema inetUser file"
  get_url:
    url: "https://raw.githubusercontent.com/CESNET/perun/{{ perun_ldap_schemas_perun_version }}/perun-utils/ldapc-scripts/schemas/inetUser-schema.ldif"
    dest: "/etc/ldap/inetUser-schema.ldif"
    force: yes
  register: inetUser_schema_file
- name: "set up schema inetUser"
  command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  /etc/ldap/inetUser-schema.ldif"
  when: inetUser_schema_entry.changed or inetUser_schema_file.changed

- name: "create entry for schema tenOperEntry"
  ldap_entry:
    dn: cn={6}tenOperEntry,cn=schema,cn=config
    objectClass: olcSchemaConfig
  register: tenOperEntry_schema_entry
- name: "download schema tenOperEntry file"
  get_url:
    url: "https://raw.githubusercontent.com/CESNET/perun/{{ perun_ldap_schemas_perun_version }}/perun-utils/ldapc-scripts/schemas/tenOperEntry-schema.ldif"
    dest: "/etc/ldap/tenOperEntry-schema.ldif"
    force: yes
  register: tenOperEntry_schema_file
- name: "set up schema tenOperEntry"
  command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f  /etc/ldap/tenOperEntry-schema.ldif"
  when: tenOperEntry_schema_entry.changed or tenOperEntry_schema_file.changed

- name: "set indexes (olcDbIndex attribute)"
  ldap_attr:
    dn: olcDatabase={1}mdb,cn=config
    name: olcDbIndex
    values:
      - cn,uid eq
      - member,memberUid eq
      - objectClass eq
      - uidNumber,gidNumber eq
      - perunVoId eq
      - eduPersonPrincipalNames eq
      - entryCSN,entryUUID eq
      - login eq
      - memberOfPerunVo eq
      - userCertificateSubject eq
      - entityID eq
      - assignedToResourceId eq
      - userIdentities eq
      - OIDCClientID eq
      - perunFacilityId eq
      - perunFacilityDn eq
      - perunUserId eq
      - perunGroupId eq
      - assignedGroupId eq
    state: exact

- name: "get OS service facts"
  when: ansible_facts.services['slapd'] is not defined
  service_facts:
